### ISSUE TITLE
Nullness checker producing initialization error for interface and abstract class objects .

### ISSUE THREAD

**Issue by ashishrana160796** [typetools/checker-framework#1831]
Considering '_AbstractProcessor_' abstract class uses a reference from interface '_ProcessingEnvironment_'  as shown below. This usage produces initialization error by nullness checker for this interface's object. Which shouldn't happen as such because it is simply illegal in java at the first place.
```
public abstract class AbstractProcessor implements Processor {
    /**
     * Processing environment providing by the tool framework.
     */
    protected ProcessingEnvironment processingEnv;
    private boolean initialized = false;
    /**
     * Constructor for subclasses to call.
     */
    protected AbstractProcessor() {}
```
With the following command :` javac -processor nullness AbstractProcessor.java` 
The following error comes : 
```
[initialization.fields.uninitialized] the constructor does not initialize fields: processingEnv
    protected AbstractProcessor() {}
```

As we know the following statement is illegal in java,
`ProcessingEnvironment processingEnv = new ProcessingEnvironment();`
which will lead to following error,
```
ProcessingEnvironment is abstract; cannot be instantiated
    	ProcessingEnvironment processingEnv = new ProcessingEnvironment();
```
 
I have referred to Chapter 3 of checker manual for this problem, but there is no analysis present with this situation. 
Here is complete bug-report attached along with java files in .txt extensions :
[BugReport.txt](https://github.com/typetools/checker-framework/files/1713231/BugReport.txt)
[AbstractProcessor.txt](https://github.com/typetools/checker-framework/files/1713232/AbstractProcessor.txt)
[ProcessingEnvironment.txt](https://github.com/typetools/checker-framework/files/1713233/ProcessingEnvironment.txt)

**Comment by mernst** [comment]
This looks like a genuine problem to me.

It's true that client code cannot call `new AbstractProcessor()`, but the AbstractProcessor constructor can still get executed.  Whenever an AbstractProcessor constructor executes, it must leave the object in a valid state.

For an example, suppose there is a subclass:

```java
class C extends AbstractProcessor {

  Object field;

  C() {
    field = new Object;
  }

}
```

Calling `new C()` would result in an incorrectly-initialized object whose `processingEnv` field is null.

Maybe there is a bug in AbstractProcessor, or maybe the `processingEnv` field is incorrectly annotated and should not have `@NonNull` type.

**Comment by ashishrana160796** [comment]
After removing non-null type from it, the AbstractProcessor will produce following errors with nullness checker analysis.
```
AbstractProcessor.java:104: error: [dereference.of.nullable] dereference of possibly-null reference processingEnv
                    processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING,
AbstractProcessor.java:128: error: [dereference.of.nullable] dereference of possibly-null reference processingEnv
                processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING
```
Hence, from this non-null type of `processingEnv` looks important but under the assumption that client will be calling `init(...)` for proper initialization  in AbstractProcessor before. Your analysis works fine with wrong type of  `processingEnv`. With this approach, still not sure with bug in AbstractProcessor.

**Comment by wmdietl** [comment]
It is not clear what `AbstractProcessor` this issue is referring to. The one from javac is not yet checked by the Nullness Checker, so errors are good.

It is no problem in Java to have a field of an interface type. That field will refer to an object that implements that interface.

`AbstractProcessor` uses lazy initialization, so the `processingEnv` field would probably need to be `@MonotonicNonNull`, `init` would need to have a post-condition that it initializes that field, and most other methods would need a pre-condition that `init` was invoked. That would be a lot of work.

Regarding this comment https://github.com/typetools/checker-framework/issues/1831#issuecomment-364708695:
The checks on a subclass of an unchecked class only give guarantees on the checked parts. The superclass `AbstractProcessor` doesn't initialize the `processingEnv` field and checking that class gives exactly that error.

Can you clarify this issue, with an independent source code example, so that we can help you?

**Comment by ashishrana160796** [comment]
@wmdietl this `AbstractProcessor` is the one from javac as pointed out here. The concerning issue is that the nullness checker demands initialization of objects of interface type and abstract class type which shouldn't be the case at all. As initialization is illegal for both of them respectively. Considering this small example code :

Consider the following interface :
```
public interface InterfaceA{
	public void test();
}
```
extended by following class A :
```
abstract class A implements InterfaceA{
	InterfaceA a;
	A()
	{
	}
}
```
The first problem comes in compiling this class as initialization of `a` is demanded. Now considering a new class B as follows :
```
public class B extends A{
	A a;
	InterfaceA ia;
	public B()
	{
	}
	public void test()
	{
	}
}
```
This demands initialization from both `a`, `ia` in this case. From my analysis of the problem this shouldn't be any of them either interface or abstract class as initializing both of them is illegal in java. @wmdietl  has suggested a solution for such problem but this initialization error shouldn't come at the first place from checker considering the rules in java.

**Comment by wmdietl** [comment]
There are (at least) three cases you could be referring to:
- Instance fields in interfaces: they don't exist in Java and don't need to be initialized.
- Instance fields in abstract classes: they are treated like fields in other classes: if they are non-null, the constructor needs to initialize them. There are no special rules for fields in abstract classes.
- Fields whose type is an interface or abstract class: such fields need to be initialized, with an object that implements the interface or a concrete subclass of the declared type. There is no special rule.

What Java rule are you referring to when you say "As initialization is illegal for both of them respectively."?

Can you please clearly point out just a single initialization error that should not occur.
If there are multiple problems, please open separate issues for each one.

**Comment by mernst** [comment]
You said:

> Consider the following interface :
> 
> public interface InterfaceA{
> 	public void test();
> }
> 
> extended by following class A :
> 
> abstract class A implements InterfaceA{
> 	InterfaceA a;
> 	A()
> 	{
> 	}
> }
> 
> The first problem comes in compiling this class as initialization of a is demanded. 

1. This has nothing to do with interfaces.  The problem exists even if class A has an Object field:

abstract class A implements InterfaceA{
	Object a;
	A()
	{
	}
}

2. "initialization of a is demanded" because that is the specification you wrote.  You have specified field `a` as `@NonNull`.  There are only two possibilities here:
 * Class A is buggy or at best error-prone, because subclasses must initialize `a` and programmers might forget to do this.  (At the very least there should be big, prominent documentation about the need for subclasses to do this.  Really the right way to do this is for the constructor of `A` to take an argument and set the field itself.
 * Your specification is incorrect:  the programmer did not intend for field `a` does not have to be non-null from the moment of construction.

I'm not going to address your second point right now, because this issue has devolved into confusions that are unrelated to its title and that should be discussed elsewhere.

**Comment by ashishrana160796** [comment]
My bad to involve two such topics into one place and taking discussion off-topic with misleading example. In which I have tried to simply use the base structure of `AbstractProcessor` problem.
@wmdietl, I am referring to `Fields whose type is an interface or abstract class` nothing else and by `illegal` it is not possible to initialize them as pointed by error in first comment . 
With @mernst explanation of `initialization of a is demanded` the issue is quite clear that is related to incorrect specification or error-prone class rather than problem in checker's analysis with either interfaces/abstract classes. Now the issue is resolved down to how to work around such code like pointed out in `AbstractProcessor`. Which I think @wmdietl's analysis of MonotonicNonNull and of preconditon `init` clears it.
Thanks.

**Comment by wmdietl** [comment]
I still don't see what you mean with "by illegal it is not possible to initialize them as pointed by error in first comment."
You simply initialize such a field with an object that implements that interface/abstract class.
But it looks like we resolved that this is not an issue with the analysis.
